;this file for FamiTone2 library generated by text2data tool
FT_DPCM_PTR=$c000

.export _game2sound_data
_game2sound_data:
;this file for FamiTone2 library generated by text2data tool

game2sound_music_data:
	.byte 1
	.word @instruments
	.word @samples-3
	.word @song0ch0,@song0ch1,@song0ch2,@song0ch3,@song0ch4,163,136 ; New song

@instruments:
	.byte $30 ;instrument $00
	.word @env1,@env0,@env0
	.byte $00

@samples:
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;1
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;2
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;3
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;4
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;5
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;6
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;7
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;8
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;9
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;10
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;11
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;12
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;13
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;14
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;15
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;16
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;17
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;18
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;19
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;20
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;21
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;22
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;23
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;24
	.byte $00+.lobyte(FT_DPCM_PTR),$18,$0f	;25
	.byte $15+.lobyte(FT_DPCM_PTR),$20,$0f	;26
	.byte $07+.lobyte(FT_DPCM_PTR),$34,$0f	;27
	.byte $1e+.lobyte(FT_DPCM_PTR),$34,$0f	;28
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;29
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;30
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;31
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;32
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;33
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;34
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;35
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;36
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;37
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;38
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;39
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;40
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;41
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;42
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;43
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;44
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;45
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;46
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;47
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;48
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;49
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;50
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;51
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;52
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;53
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;54
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;55
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;56
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;57
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;58
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;59
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;60
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;61
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;62
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;63

@env0:
	.byte $c0,$00,$00
@env1:
	.byte $cf,$0f,$cf,$00,$02


; New song
@song0ch0:
	.byte $fb,$02
@song0ch0loop:
@ref0:
	.byte $f9,$85
@ref1:
	.byte $f9,$85
@ref2:
	.byte $f9,$85
@ref3:
	.byte $f9,$85
@ref4:
	.byte $f9,$85
@ref5:
	.byte $f9,$85
@ref6:
	.byte $f9,$85
@ref7:
	.byte $f9,$85
	.byte $fd
	.word @song0ch0loop

; New song
@song0ch1:
@song0ch1loop:
@ref8:
	.byte $80,$14,$85,$22,$85,$2c,$85,$22,$85,$32,$85,$22,$85,$36,$85,$22
	.byte $85,$38,$85,$22,$85,$36,$85,$32,$8d,$22,$85,$32,$85,$30,$85
@ref9:
	.byte $14,$85,$22,$85,$2c,$85,$22,$85,$32,$85,$22,$85,$36,$85,$22,$85
	.byte $38,$85,$22,$85,$36,$85,$32,$8d,$22,$85,$32,$85,$30,$85
	.byte $ff,$1e
	.word @ref9
	.byte $ff,$1e
	.word @ref9
@ref12:
	.byte $14,$8d,$14,$85,$14,$85,$1a,$8d,$14,$85,$14,$85,$20,$85,$1e,$8d
	.byte $1a,$8d,$18,$8d,$14,$85
@ref13:
	.byte $87,$14,$85,$14,$85,$0a,$85,$10,$85,$14,$85,$1e,$85,$20,$8d,$20
	.byte $8d,$1e,$85,$17,$1b,$17,$1b,$17,$1b,$17,$1a,$81
	.byte $ff,$16
	.word @ref12
@ref15:
	.byte $0c,$8d,$02,$85,$10,$8d,$02,$85,$14,$cd
	.byte $fd
	.word @song0ch1loop

; New song
@song0ch2:
@song0ch2loop:
@ref16:
	.byte $f9,$85
@ref17:
	.byte $f9,$85
@ref18:
	.byte $f9,$85
@ref19:
	.byte $f9,$85
@ref20:
	.byte $f9,$85
@ref21:
	.byte $f9,$85
@ref22:
	.byte $f9,$85
@ref23:
	.byte $f9,$85
	.byte $fd
	.word @song0ch2loop

; New song
@song0ch3:
@song0ch3loop:
@ref24:
	.byte $f9,$85
@ref25:
	.byte $f9,$85
@ref26:
	.byte $f9,$85
@ref27:
	.byte $f9,$85
@ref28:
	.byte $f9,$85
@ref29:
	.byte $f9,$85
@ref30:
	.byte $f9,$85
@ref31:
	.byte $f9,$85
	.byte $fd
	.word @song0ch3loop

; New song
@song0ch4:
@song0ch4loop:
@ref32:
	.byte $f9,$85
@ref33:
	.byte $f9,$85
@ref34:
	.byte $f9,$85
@ref35:
	.byte $f9,$85
@ref36:
	.byte $f9,$85
@ref37:
	.byte $f9,$85
@ref38:
	.byte $f9,$85
@ref39:
	.byte $f9,$85
	.byte $fd
	.word @song0ch4loop
